apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: db
spec:
  limits:
    - default:
        memory: "500Mi"
      defaultRequest:
        memory: "256Mi"
      type: Container
