apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.mem.name }}
  namespace: {{ template "namespace" . }}
spec:
  limits:
   {{- with .Values.mem.limits }}
    - default:
        cpu: {{ .default.memory }}
      defaultRequest:
        cpu: {{ .defaultRequest.memory }}
      type: {{ .type }}
   {{- end }}
