
{{- if not .Values.ingress.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-nginx-php
  namespace: {{ template "namespace" . }}
spec:
  type: NodePort
  {{- with .Values.service }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
  {{- end }}
  selector:
      {{- template "labels" . }}

{{- end }}