apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-php-db-secret
  namespace: {{ template "namespace" . }}
data:
  {{- with .Values.secret }}
  DB_PASSWORD: {{ .passwd }}
  DB_DATABASE: {{ .db }}
  {{- end }}
