apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.pvclaim.name }}
  namespace: {{ template "namespace" . }}
spec:
  {{- with .Values.pvclaim }}
  accessModes:
  - {{ .accessModes }}
  resources:
    requests:
      storage: {{ .storage }}
  {{- end }}



