apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.headlessService.name }}
  namespace: {{ template "namespace" . }}
spec:
  {{- with .Values.headlessService }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetport }}
  {{- end }}
  clusterIP: {{ .clusterIP }} # that is make headless service that send trafic only one pod that you have specified in statefless-0 pod
  selector:
  {{- template "labels" . }}
