apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.memory.name }}
  namespace: {{ template "namespace" . }}
spec:
  limits:
  {{- with .Values.memory.limits }}
    - default:
        cpu: {{ .default.memory }}
      defaultRequest:
        cpu: {{ .defaultRequest.memory }}
      type: {{ .type }}
  {{- end }}