apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ .Values.networkPolicy.name }}
  namespace: {{ template "namespace" . }}
spec:
  podSelector:
    matchLabels:
    {{ include "networkPolicyLabels" . | indent 2 }}
  policyTypes:
  {{- range .Values.networkPolicy.policyTypes }}
   - {{ . }}
  {{- end }}

  ingress:
    - from:
        # allow  pod matchinng pod-selector label within web-ns namespace on port 3306
        - namespaceSelector:
            matchLabels:
              ns: {{ .Values.networkPolicy.ingress.namespaceLabels.ns }}
          podSelector:
            matchLabels:
            {{ include "networkPolicyIngressLabels" . | indent 10 }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.ingress.port }}
          
  # egress:
  #   - to:
  #       - ipBlock:
  #           cidr: 10.0.0.0/24
  #     ports:
  #       - protocol: TCP
  #         port: 5978
