{{- with .Values.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ template "namespace" . }}
provisioner: {{ .provisioner }}
parameters:
  type: {{ .type }}
volumeBindingMode: {{ .volumeBindingMode }}
{{- end }}
