
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-{{ .Values.storageClass.name }}
  namespace: {{ template "namespace" . }}
{{- with .Values.storageClass }}
provisioner: {{ .provisioner }}
parameters:
  type: {{ .type }}
volumeBindingMode: {{ .volumeBindingMode }}
{{- end }}
