{
 "title": "EKS Cluster (Prometheus)",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": { "query": "label_values(node)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health(global)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster Pod Capacity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "pods" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_info{node=~\"$node\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster CPU Usage(global)",
     "type": "gauge",
     "description": " global CPU usage for k8s cluster in percentage",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$interval]))\n    /\n  sum(kube_node_status_capacity{resource=\"cpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster Memory Usage(global)",
     "type": "gauge",
     "description": "global memory usage for k8s cluster in percentage",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  sum(container_memory_usage_bytes{container!=\"\"})\n    /\n  sum(kube_node_status_capacity{resource=\"memory\"})\n)"
      }
     ]
    },
    {
     "title": "Cluster Disk Usage(global)",
     "type": "gauge",
     "description": "global memory usage for k8s cluster in percentage",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (100 * (sum(node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} )  / sum(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) ))\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statefulset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ statefulset }}"
      }
     ]
    },
    {
     "title": "Statefulset Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Statefulset Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Node(All)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Nodes Out of Disk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Uptime (All- server)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "time()-node_boot_time_seconds", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "CPU utilization(All-server)",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " 100- ( sum(node_cpu_seconds_total{mode=\"idle\"}) by (instance) / sum(node_cpu_seconds_total) by (instance) *100) \n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "free disk space ",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (mountpoint,instance) (node_filesystem_avail_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk utilization (All- server)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) - (node_filesystem_free_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Utilization(irate1m)(All-server)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Disk(All- server)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods Running",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pod information",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=\"$namespace\"}",
       "legendFormat": "{{ pod_ip }}"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Resources by containers",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 7, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) by (container)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\", container!=\"\"}[$__rate_interval])) by (container)",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",  image!=\"\", container!=\"\"}) by (container)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "CPU Usage by containers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\", container!=\"\"}[$__rate_interval])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
      }
     ]
    },
    {
     "title": "Memory Usage by containers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", container!=\"\"}) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 14, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 14, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Succeeded(active)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  }
 ]
}