######### PHP-deployment ##############
replicaCount: 1
namespace: dev
labels:
  dp: dp-nginx-php
  web: nginx-php
  tier: front-end
  ns: web-ns
  exporter: phpfpm
  svc: php-fpm-exporter

image:
  php:
    repository: 975263414773.dkr.ecr.us-east-1.amazonaws.com/php-web-app
    tag: 3ca115c963a5365bf7fe1e08dced708d3932a775
  nginx:
    repository: nginx
    tag: latest
  php_fpm_exporter:
    repository: quay.io/sysdig/php-fpm-exporter
    tag: v2.3.3

containers:
  php:
    name: php-ctr
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        cpu: "500m"
        memory: "200Mi"

  nginx:
    name: nginx-ctr
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        cpu: "500m"
        memory: "200Mi"
  php_fpm_exporter:
    name: php-fpm-exporter

ports:
  nginx: 80
  php: 9000
  php_fpm_exporter: 9253

phpExporterenv:
  PHP_FPM_WEB_LISTEN_ADDRESS: ":9253"
  PHP_FPM_WEB_TELEMETRY_PATH: /metrics
  PHP_FPM_FIX_PROCESS_COUNT: "false"
  PHP_FPM_LOG_LEVEL: info
  PHP_FPM_SCRAPE_URI:
    protocol: tcp://
    address: svc-nginx-php:9000
    path: /status

## node affinity
nodeAffinity:
  key: node
  operator: In
  values:
    - kubenode02
    - kubemaster
    - minikube

## toleration

tolerations:
  a:
    key: "color"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
    # tolerationSeconds: 10
  b:
    key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
    # tolerationSeconds: 10

## cpu and memory limit
cpu:
  name: cpu-limit-range
  limits:
    default:
      cpu: "500m"
    defaultRequest:
      cpu: "50m"
    type: Container

mem:
  name: mem-limit-range
  limits:
    default:
      memory: "300Mi"
    defaultRequest:
      memory: "100Mi"
    type: Container

## Volumes

volumes:
  vol1: nginx-config-volume
  vol2: shared-files
  vol3: php-fpm-config

volumeMounts:
  web: /var/www/html/
  nginxConf: /etc/nginx/conf.d/
  php_fpm:
    path: /usr/local/etc/php-fpm.d/www.conf
    subpath: www.conf
## ConfigMap

configmap:
  nginx: nginx-config
  phpdb: php-db-configmap
  php_fpm: php-fpm-config
  php_fpm_exporter: php-fpm-exporter
  dbHost:
    statefullName: mariadb-st-0
    name: db-h
    namespace: db
    domain: svc.cluster.local

  dbUser: deepak

## secret

secret:
  phpdb: php-db-secret
  passwd: ZGVlcGFrMTIz
  db: ZWNvbWRi

## Service

service:
  nginx:
    name: nginx
    port: 80
    targetPort: 80
    nodePort: 30006
  php_fpm:
    name: php-fpm
    port: 9000
    targetPort: 9000
  php_fpm_exporter:
    name: php-fpm-exporter
    port: 9253
    targetPort: 9253

########### Ingress #######################

ingress:
  create: true
  namespace: ingress-nginx
  name: ingress-php
  class: "nginx"
  rewriteTarget: /
  path: /
  backend:
    service:
      name: php-service-external
      port: 80
