- hosts: localhost
  connection: local
  tasks:
    - name: "helm release output"
      become: yes
      register: release
      shell: "helm list -q | tr '\\n' ','"

    - name: "test"
      debug:
        msg: "{{ release.stdout }}"

    - name: "workspace"
      become: yes
      shell: "echo ${WORKSPACE} >/home/ubuntu/work"

    - name: "repo"
      become: yes
      shell: "echo ${REPOSITORY_URI} >/home/ubuntu/repo"

    - name: "taggit"
      become: yes
      shell: "echo ${GIT_COMMIT_HASH} >/home/ubuntu/gittag"

    - name: "install helm chart if not exists"
      become: yes
      shell: "helm install php ${WORKSPACE}/helm/php-nginx-chart/"
      when: release.stdout | length ==  0

    - name: "install ingress controller if not exists"
      become: yes
      shell: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/cloud/deploy.yaml"
      when: release.stdout | length ==  0

    - name: "upgrading helm chart"
      become: yes
      shell: "helm upgrade --set image.php.repository=${REPOSITORY_URI} --set image.php.tag=${GIT_COMMIT_HASH} php ${WORKSPACE}/helm/php-nginx-chart/"
      when: release.stdout | length > 0
