apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-php
  namespace: dev
spec:
  # type: NodePort
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30006
  selector:
    web: nginx-php
    tier: front-end
